// The error bytes added onto the end of a D64 or D71 disk image are populated
// by a CODE that is the same as that generated by the 1541 drive controller.
// It reports these numbers, not the error code usually seen on the Commodore
// computer when an error occurs on a real disk drive.
package disk

const (
	None fdcJob = iota // actually an N/A
	Seek
	Read
	Decode
	Write
)

type fdcJob uint8
type fdcCode uint8

type dosError struct {
	ipCode  uint8
	request fdcJob
	d64     bool
	message string
}

// See the `docs.md` for a more detailed explanation of these codes and descriptions.
var errorCodes = map[fdcCode]dosError{
	0x01: {00, None, true, "OK"},
	0x02: {20, Seek, true, "Header Block / Descriptor Byte Not Found"},
	0x03: {21, Seek, true, "No SYNC Sequence Found"},
	0x04: {22, Read, true, "Data Descriptor Byte Not Found"},
	0x05: {23, Read, true, "Checksum Error in Data Block"},
	0x06: {24, Write, false, "Write-Verify on Format"}, // never occurs on 1541
	0x07: {25, Write, false, "Write-Verify Error"},
	0x08: {26, Write, false, "Write Protect On"},
	0x09: {27, Seek, true, "Checksum Error in Header Block"},
	0x0A: {28, Write, false, "Write Error"}, // never occurs on 1541
	0x0B: {29, Seek, true, "Disk Sector ID Mismatch"},
	0x0F: {74, Read, false, "Drive Not Ready (no disk in drive or no device 1)"},
}
